-- ==============================================================================
-- cassette.fm — Supabase Database Schema & Row Level Security (RLS) Policies
-- ==============================================================================
-- Instructions:
-- 1. Open your Supabase Project Dashboard: https://app.supabase.com
-- 2. Navigate to "SQL Editor" in the left sidebar.
-- 3. Click "New query", paste this entire script, and click "Run".
-- ==============================================================================

-- 1. LIKED SONGS TABLE
-- Stores tracks liked/favorited by users with full metadata JSON
create table if not exists public.liked_songs (
    user_id uuid not null references auth.users(id) on delete cascade,
    song_id text not null,
    song_data jsonb not null,
    created_at timestamptz not null default now(),
    primary key (user_id, song_id)
);

-- 2. USER PLAYLISTS TABLE
-- Stores custom user-curated playlists with track lists and cover art
create table if not exists public.user_playlists (
    id text not null primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    description text default '',
    songs jsonb not null default '[]'::jsonb,
    thumbnail text default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 3. PLAYBACK HISTORY TABLE
-- Stores recent listening history for infinite resume & recommendation tuning
create table if not exists public.playback_history (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    song_id text not null,
    song_data jsonb not null,
    played_at timestamptz not null default now()
);

-- ==============================================================================
-- 4. PERFORMANCE INDEXES
-- ==============================================================================
create index if not exists idx_liked_songs_user on public.liked_songs(user_id);
create index if not exists idx_user_playlists_user on public.user_playlists(user_id);
create index if not exists idx_playback_history_user on public.playback_history(user_id, played_at desc);

-- ==============================================================================
-- 5. ENABLE ROW LEVEL SECURITY (RLS)
-- ==============================================================================
alter table public.liked_songs enable row level security;
alter table public.user_playlists enable row level security;
alter table public.playback_history enable row level security;

-- ==============================================================================
-- 6. RLS POLICIES FOR LIKED SONGS
-- ==============================================================================
drop policy if exists "Users can view own liked songs" on public.liked_songs;
create policy "Users can view own liked songs"
    on public.liked_songs for select
    using (auth.uid() = user_id);

drop policy if exists "Users can insert own liked songs" on public.liked_songs;
create policy "Users can insert own liked songs"
    on public.liked_songs for insert
    with check (auth.uid() = user_id);

drop policy if exists "Users can update own liked songs" on public.liked_songs;
create policy "Users can update own liked songs"
    on public.liked_songs for update
    using (auth.uid() = user_id);

drop policy if exists "Users can delete own liked songs" on public.liked_songs;
create policy "Users can delete own liked songs"
    on public.liked_songs for delete
    using (auth.uid() = user_id);

-- ==============================================================================
-- 7. RLS POLICIES FOR USER PLAYLISTS
-- ==============================================================================
drop policy if exists "Users can view own playlists" on public.user_playlists;
create policy "Users can view own playlists"
    on public.user_playlists for select
    using (auth.uid() = user_id);

drop policy if exists "Users can insert own playlists" on public.user_playlists;
create policy "Users can insert own playlists"
    on public.user_playlists for insert
    with check (auth.uid() = user_id);

drop policy if exists "Users can update own playlists" on public.user_playlists;
create policy "Users can update own playlists"
    on public.user_playlists for update
    using (auth.uid() = user_id);

drop policy if exists "Users can delete own playlists" on public.user_playlists;
create policy "Users can delete own playlists"
    on public.user_playlists for delete
    using (auth.uid() = user_id);

-- ==============================================================================
-- 8. RLS POLICIES FOR PLAYBACK HISTORY
-- ==============================================================================
drop policy if exists "Users can view own history" on public.playback_history;
create policy "Users can view own history"
    on public.playback_history for select
    using (auth.uid() = user_id);

drop policy if exists "Users can insert own history" on public.playback_history;
create policy "Users can insert own history"
    on public.playback_history for insert
    with check (auth.uid() = user_id);

drop policy if exists "Users can delete own history" on public.playback_history;
create policy "Users can delete own history"
    on public.playback_history for delete
    using (auth.uid() = user_id);
